// for quiz 1: do an image (screenshot of modified periodic table) as question, or
// bother with the formatting of a square div with border with element symbol in middle?

export const allQuizzes = [
    // Quiz 1, Element name
    [
        {
            questionNumber: 1,
            question: "H",
            answers: ["Hafnium", "Hydrogen", "Helium", "Holmium"],
            correctAnswer: "Hydrogen",
            imgSrc: "",
        },
        {
            questionNumber: 2,
            question: "Na",
            answers: ["Sodium", "Neodymium", "Niobium", "Napthalene"],
            correctAnswer: "Sodium",
            imgSrc: "",
        },
        {
            questionNumber: 3,
            question: "Mn",
            answers: ["Manganese", "Magnesium", "Moscovium", "Molybdenum"],
            correctAnswer: "Manganese",
            imgSrc: "",
        },
        {
            questionNumber: 4,
            question: "Au",
            answers: ["Antimony", "Arsenic", "Astatine", "Gold"],
            correctAnswer: "Gold",
            imgSrc: "",
        },
        {
            questionNumber: 5,
            question: "N",
            answers: ["Neodymium", "Niobium", "Nitrogen", "Nihonium"],
            correctAnswer: "Nitrogen",
            imgSrc: "",
        },
        {
            questionNumber: 6,
            question: "C",
            answers: ["Carbon", "Zinc", "Cerium", "Calcium"],
            correctAnswer: "Carbon",
            imgSrc: "",
        },
        {
            questionNumber: 7,
            question: "Ag",
            answers: ["Actinium", "Silver", "Arsenic", "Platinum"],
            correctAnswer: "Silver",
            imgSrc: "",
        },
        {
            questionNumber: 8,
            question: "O",
            answers: ["Thorium", "Oganesson", "Oxygen", "Osmium"],
            correctAnswer: "Oxygen",
            imgSrc: "",
        },
        {
            questionNumber: 9,
            question: "Fe",
            answers: ["Fermium", "Francium", "Flerovium", "Iron"],
            correctAnswer: "Iron",
            imgSrc: "",
        },
        {
            questionNumber: 10,
            question: "Pb",
            answers: ["Lead", "Platinum", "Protactinium", "Tin"],
            correctAnswer: "Lead",
            imgSrc: "",
        },
        {
            questionNumber: 11,
            question: "B",
            answers: ["Bohrium", "Bismuth", "Ytterbium", "Boron"],
            correctAnswer: "Boron",
            imgSrc: "",
        },
        {
            questionNumber: 12,
            question: "Cm",
            answers: ["Cadmium", "Copper", "Curium", "Cesium"],
            correctAnswer: "Curium",
            imgSrc: "",
        },
        {
            questionNumber: 13,
            question: "Sn",
            answers: ["Antimony", "Samarium", "Tin", "Seaborgium"],
            correctAnswer: "Tin",
            imgSrc: "",
        },
        {
            questionNumber: 14,
            question: "K",
            answers: ["Calcium", "Potassium", "Krypton", "Copper"],
            correctAnswer: "Potassium",
            imgSrc: "",
        },
        {
            questionNumber: 15,
            question: "Ti",
            answers: ["Titanium", "Terbium", "Thallium", "Thulium"],
            correctAnswer: "Titanium",
            imgSrc: "",
        },
        {
            questionNumber: 16,
            question: "Sb",
            answers: ["Samarium", "Seaborgium", "Antimony", "Scandium"],
            correctAnswer: "Antimony",
            imgSrc: "",
        },
        {
            questionNumber: 17,
            question: "Pt",
            answers: ["Palladium", "Plutonium", "Platinum", "Protactinium"],
            correctAnswer: "Platinum",
            imgSrc: "",
        },
        {
            questionNumber: 18,
            question: "Ni",
            answers: ["Nobelium", "Nihonium", "Niobium", "Nickel"],
            correctAnswer: "Nickel",
            imgSrc: "",
        },
        {
            questionNumber: 19,
            question: "V",
            answers: ["Flerovium", "Vanadium", "Livermorium", "Mendelevium"],
            correctAnswer: "Vanadium",
            imgSrc: "",
        },
        {
            questionNumber: 20,
            question: "W",
            answers: ["Tungsten", "Zirconium", "Iridium", "Mercury"],
            correctAnswer: "Tungsten",
            imgSrc: "",
        },
    ],
    // Quiz #2, element trivia
    [],
    // Quiz #3, molecular formulae
    [
        {
            questionNumber: 1,
            question: "",
            imgSrc: "./quiz3images/q1.png",
            answers: ["Nitrogen Hydride", "Ammonium", "Hydronium", "Nitrazine"],
            correctAnswer: "Ammonium",
        },
        {
            questionNumber: 2,
            question: "",
            imgSrc: "./quiz3images/q2.png",
            answers: [
                "Carbonate",
                "Carbon trioxide",
                "Carbide",
                "Carbolic acid",
            ],
            correctAnswer: "Carbonate",
        },
        {
            questionNumber: 3,
            question: "",
            imgSrc: "./quiz3images/q3.png",
            answers: [
                "Carbon hydroxide",
                "Phenol",
                "Bicarbonate",
                "Hydrogen trioxide",
            ],
            correctAnswer: "Bicarbonate",
        },
        {
            questionNumber: 4,
            question: "",
            imgSrc: "./quiz3images/q4.png",
            answers: [
                "Dihydrogen tetroxide",
                "Hydronium",
                "Hydroxide",
                "Water",
            ],
            correctAnswer: "Water",
        },
        {
            questionNumber: 5,
            question: "",
            imgSrc: "./quiz3images/q5.png",
            answers: ["Hydroxide", "Hydrogen dioxide", "Monoxide", "Cyanide"],
            correctAnswer: "Hydroxide",
        },
        {
            questionNumber: 6,
            question: "",
            imgSrc: "./quiz3images/q6.png",
            answers: [
                "Hydronium",
                "Trihydrogen dioxide",
                "Hydrogen superoxide",
                "Perchlorate",
            ],
            correctAnswer: "Hydronium",
        },
        {
            questionNumber: 7,
            question: "",
            imgSrc: "./quiz3images/q7.png",
            answers: ["Superoxide", "Peroxide", "Dioxide", "Peroxidate"],
            correctAnswer: "Peroxide",
        },
        {
            questionNumber: 8,
            question: "",
            imgSrc: "./quiz3images/q8.png",
            answers: ["Sulfate", "Iodate", "Carbonate", "Chloride"],
            correctAnswer: "Chloride",
        },
        {
            questionNumber: 9,
            question: "",
            imgSrc: "./quiz3images/q9.png",
            answers: [
                "Sulfide",
                "Chlorate",
                "Chlorine trioxide",
                "Perchlorate",
            ],
            correctAnswer: "Chlorate",
        },
        {
            questionNumber: 10,
            question: "",
            imgSrc: "./quiz3images/q10.png",
            answers: [
                "Chloridinium",
                "Chlorine oxide",
                "Hypochlorite",
                "Perchlorate",
            ],
            correctAnswer: "Hypochlorite",
        },
        {
            questionNumber: 11,
            question: "",
            imgSrc: "./quiz3images/q11.png",
            answers: [
                "Carbon monoxide",
                "Carbon oxalate",
                "Thiosulfate",
                "Carbonate",
            ],
            correctAnswer: "Carbon monoxide",
        },
        {
            questionNumber: 12,
            question: "",
            imgSrc: "./quiz3images/q12.png",
            answers: [
                "Carbon nitride",
                "Cyanide",
                "Carboninium",
                "Carbon nitrate",
            ],
            correctAnswer: "Cyanide",
        },
        {
            questionNumber: 13,
            question: "",
            imgSrc: "./quiz3images/q13.png",
            answers: [
                "Carbon hydroxide",
                "Bicarbonate",
                "Acetate",
                "Carboninium",
            ],
            correctAnswer: "Acetate",
        },
        {
            questionNumber: 14,
            question: "",
            imgSrc: "./quiz3images/q14.png",
            answers: [
                "Nitrous oxalate",
                "Nitrogen monoxide",
                "Nitrate",
                "Nitrite",
            ],
            correctAnswer: "Nitrogen monoxide",
        },
        {
            questionNumber: 15,
            question: "",
            imgSrc: "./quiz3images/q15.png",
            answers: [
                "Nitrate",
                "Nitrotoluene",
                "Nitrogen trioxide",
                "Nitrite",
            ],
            correctAnswer: "Nitrate",
        },
        {
            questionNumber: 16,
            question: "",
            imgSrc: "./quiz3images/q16.png",
            answers: ["Sulfur", "Sulfate", "Persulfide", "Sulfide"],
            correctAnswer: "Sulfide",
        },
        {
            questionNumber: 17,
            question: "",
            imgSrc: "./quiz3images/q17.png",
            answers: [
                "Sulfur tetroxide",
                "Persulfide",
                "Sulfate",
                "Sulfurous oxide",
            ],
            correctAnswer: "Sulfate",
        },
        {
            questionNumber: 18,
            question: "",
            imgSrc: "./quiz3images/q18.png",
            answers: [
                "Sulfur peroxide",
                "Phosphorus tetroxide",
                "Phosgene",
                "Phosphate",
            ],
            correctAnswer: "Phosphate",
        },
        {
            questionNumber: 19,
            question: "",
            imgSrc: "./quiz3images/q19.png",
            answers: [
                "Manganese tetroxide",
                "Permanganate",
                "Manganate",
                "Manganese superoxide",
            ],
            correctAnswer: "Permanganate",
        },
        {
            questionNumber: 20,
            question: "",
            imgSrc: "./quiz3images/q20.png",
            answers: [
                "Chromium tetroxide",
                "Perchromate",
                "Chromate",
                "Chromium superoxide",
            ],
            correctAnswer: "Chromate",
        },
    ],
    // Quiz #4, biological molecules
    [
        {
            questionNumber: 1,
            question: "",
            imgSrc: "./quiz4images/q1.png",
            answers: ["Myosin II", "Collagen", "Hemoglobin", "Trypsin"],
            correctAnswer: "Hemoglobin",
        },
        {
            questionNumber: 2,
            question: "",
            imgSrc: "./quiz4images/q2.png",
            answers: ["Heme", "Chloryphyll a", "Biotin", "Cytochrome c"],
            correctAnswer: "Heme",
        },
        {
            questionNumber: 3,
            question: "",
            imgSrc: "./quiz4images/q3.png",
            answers: [
                "Triacylglyceride",
                "Palmitic acid",
                "Phosphatidylserine",
                "Ethanolamine",
            ],
            correctAnswer: "Phosphatidylserine",
        },
        {
            questionNumber: 4,
            question: "",
            imgSrc: "./quiz4images/q4.png",
            answers: [
                "Diacylglyceride",
                "Arachidonic acid",
                "Phosphatidylcholine",
                "Phosphatidyl inositol",
            ],
            correctAnswer: "Arachidonic acid",
        },
        {
            questionNumber: 5,
            question: "",
            imgSrc: "./quiz4images/q5.png",
            answers: [
                "Formic acid",
                "Trihydroxy propane",
                "Inositol",
                "Glycerol",
            ],
            correctAnswer: "Glycerol",
        },
        {
            questionNumber: 6,
            question: "",
            imgSrc: "./quiz4images/q6.png",
            answers: [
                "Choline",
                "Oxaloacetate",
                "Dihydroxy acetone",
                "Glycerol",
            ],
            correctAnswer: "Choline",
        },
        {
            questionNumber: 7,
            question: "",
            imgSrc: "./quiz4images/q7.png",
            answers: ["Carnitine", "Glutathione", "Glutamine", "Isocitrate"],
            correctAnswer: "Carnitine",
        },
        {
            questionNumber: 8,
            question: "",
            imgSrc: "./quiz4images/q8.png",
            answers: ["Flavin", "Thiamine", "Cholesterol", "Estrone"],
            correctAnswer: "Cholesterol",
        },
        {
            questionNumber: 9,
            question: "",
            imgSrc: "./quiz4images/q9.png",
            answers: ["Testosterone", "Estriol", "Progesterone", "Lipoate"],
            correctAnswer: "Testosterone",
        },
        {
            questionNumber: 10,
            question: "",
            imgSrc: "./quiz4images/q10.png",
            answers: ["Progesterone", "Epinephrine", "Estradiol", "Cortisol"],
            correctAnswer: "Estradiol",
        },
        {
            questionNumber: 11,
            question: "",
            imgSrc: "./quiz4images/q11.png",
            answers: ["Adenosine", "NADH", "Riboflavin", "Cytochrome c"],
            correctAnswer: "NADH",
        },
        {
            questionNumber: 12,
            question: "",
            imgSrc: "./quiz4images/q12.png",
            answers: ["Ribulose", "Flavin", "Guanine", "Lipoamide"],
            correctAnswer: "Flavin",
        },
        {
            questionNumber: 13,
            question: "",
            imgSrc: "./quiz4images/q13.png",
            answers: [
                "Alpha-D-Galactose",
                "D-Fucose",
                "L-Galactose",
                "Beta-D-Glucose",
            ],
            correctAnswer: "Beta-D-Glucose",
        },
        {
            questionNumber: 14,
            question: "",
            imgSrc: "./quiz4images/q14.png",
            answers: ["D-Fructose", "D-Mannose", "L-Erythrose", "L-Arabinose"],
            correctAnswer: "D-Fructose",
        },
        {
            questionNumber: 15,
            question: "",
            imgSrc: "./quiz4images/q15.png",
            answers: ["Citrate", "Malate", "Fumarate", "Oxaloacetate"],
            correctAnswer: "Oxaloacetate",
        },
        {
            questionNumber: 16,
            question: "",
            imgSrc: "./quiz4images/q16.png",
            answers: ["Bisphenol A", "1,3-BPG", "Biotin", "Napthoquinone"],
            correctAnswer: "Biotin",
        },
        {
            questionNumber: 17,
            question: "",
            imgSrc: "./quiz4images/q17.png",
            answers: ["Ribose", "Xylose", "Mannose", "Lactose"],
            correctAnswer: "Ribose",
        },
        {
            questionNumber: 18,
            question: "",
            imgSrc: "./quiz4images/q18.png",
            answers: ["Cobalamin", "Adenine", "Uracil", "Lipoic acid"],
            correctAnswer: "Adenine",
        },
        {
            questionNumber: 19,
            question: "",
            imgSrc: "./quiz4images/q19.png",
            answers: [
                "Thymine",
                "4-hydroxyproline",
                "Pyridoxine",
                "Nicotinic acid",
            ],
            correctAnswer: "Thymine",
        },
        {
            questionNumber: 20,
            question: "",
            imgSrc: "./quiz4images/q20.png",
            answers: ["Guanine", "Caffeine", "Cytosine", "Xanthine"],
            correctAnswer: "Caffeine",
        },
    ],
    // Quiz #5, amino acids
    [
        {
            questionNumber: 1,
            question: "",
            imgSrc: "./quiz5images/q1.png",
            answers: ["Valine", "Tyrosine", "Proline", "Phenylalanine"],
            correctAnswer: "Phenylalanine",
        },
        {
            questionNumber: 2,
            question: "",
            imgSrc: "./quiz5images/q2.png",
            answers: ["Tryptophan", "Serine", "Glycine", "Glutamine"],
            correctAnswer: "Glycine",
        },
        {
            questionNumber: 3,
            question: "",
            imgSrc: "./quiz5images/q3.png",
            answers: ["Methionine", "Isoleucine", "Asparagine", "Lysine"],
            correctAnswer: "Asparagine",
        },
        {
            questionNumber: 4,
            question: "",
            imgSrc: "./quiz5images/q4.png",
            answers: ["Cysteine", "Arginine", "Threonine", "Tyrosine"],
            correctAnswer: "Cysteine",
        },
        {
            questionNumber: 5,
            question: "",
            imgSrc: "./quiz5images/q5.png",
            answers: ["Alanine", "Histidine", "Serine", "Isoleucine"],
            correctAnswer: "Isoleucine",
        },
        {
            questionNumber: 6,
            question: "",
            imgSrc: "./quiz5images/q6.png",
            answers: ["Lysine", "Threonine", "Methionine", "Valine"],
            correctAnswer: "Threonine",
        },
        {
            questionNumber: 7,
            question: "",
            imgSrc: "./quiz5images/q7.png",
            answers: ["Phenylalanine", "Glycine", "Proline", "Glutamate"],
            correctAnswer: "Proline",
        },
        {
            questionNumber: 8,
            question: "",
            imgSrc: "./quiz5images/q8.png",
            answers: ["Glutamine", "Aspartate", "Asparagine", "Serine"],
            correctAnswer: "Glutamine",
        },
        {
            questionNumber: 9,
            question: "",
            imgSrc: "./quiz5images/q9.png",
            answers: ["Asparagine", "Leucine", "Alanine", "Valine"],
            correctAnswer: "Valine",
        },
        {
            questionNumber: 10,
            question: "",
            imgSrc: "./quiz5images/q10.png",
            answers: ["Histidine", "Tyrosine", "Glutamate", "Tryptophan"],
            correctAnswer: "Tyrosine",
        },
        {
            questionNumber: 11,
            question: "",
            imgSrc: "./quiz5images/q11.png",
            answers: ["Lysine", "Asparagine", "Leucine", "Arginine"],
            correctAnswer: "Lysine",
        },
        {
            questionNumber: 12,
            question: "",
            imgSrc: "./quiz5images/q12.png",
            answers: ["Alanine", "Arginine", "Asparagine", "Aspartate"],
            correctAnswer: "Aspartate",
        },
        {
            questionNumber: 13,
            question: "",
            imgSrc: "./quiz5images/q13.png",
            answers: ["Arginine", "Asparagine", "Alanine", "Phenylalanine"],
            correctAnswer: "Alanine",
        },
        {
            questionNumber: 14,
            question: "",
            imgSrc: "./quiz5images/q14.png",
            answers: ["Serine", "Arginine", "Cysteine", "Threonine"],
            correctAnswer: "Arginine",
        },
        {
            questionNumber: 15,
            question: "",
            imgSrc: "./quiz5images/q15.png",
            answers: ["Tryptophan", "Threonine", "Tyrosine", "Histidine"],
            correctAnswer: "Tryptophan",
        },
        {
            questionNumber: 16,
            question: "",
            imgSrc: "./quiz5images/q16.png",
            answers: ["Serine", "Leucine", "Methionine", "Lysine"],
            correctAnswer: "Methionine",
        },
        {
            questionNumber: 17,
            question: "",
            imgSrc: "./quiz5images/q17.png",
            answers: ["Leucine", "Glutamate", "Methionine", "Glutamine"],
            correctAnswer: "Leucine",
        },
        {
            questionNumber: 18,
            question: "",
            imgSrc: "./quiz5images/q18.png",
            answers: ["Glycine", "Serine", "Cysteine", "Proline"],
            correctAnswer: "Serine",
        },
        {
            questionNumber: 19,
            question: "",
            imgSrc: "./quiz5images/q19.png",
            answers: ["Histidine", "Tyrosine", "Proline", "Methionine"],
            correctAnswer: "Histidine",
        },
        {
            questionNumber: 20,
            question: "",
            imgSrc: "./quiz5images/q20.png",
            answers: ["Threonine", "Arginine", "Glutamate", "Asparagine"],
            correctAnswer: "Glutamate",
        },
    ],
];
